# Generated by Django 2.1.4 on 2018-12-14 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuid', models.IntegerField()),
                ('title', models.CharField(max_length=300)),
                ('cat', models.CharField(choices=[('Programming', 'Programming'), ('Graphic Design', 'Graphic Design'), ('Networking', 'Networking'), ('Database', 'Database'), ('Web Design', 'Web Design'), ('REST API', 'REST API'), ('Linux', 'Linux'), ('Photography', 'Photography'), ('Geranal', 'General')], max_length=60)),
                ('date_published', models.DateTimeField(default=datetime.datetime.now)),
                ('s_desc', models.TextField(blank=True)),
                ('l_desc', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('photo_1', models.ImageField(upload_to='photos/%y/%m/%d/')),
                ('photo_2', models.ImageField(upload_to='photos/%y/%m/%d/')),
                ('photo_3', models.ImageField(upload_to='photos/%y/%m/%d/')),
                ('photo_4', models.ImageField(upload_to='photos/%y/%m/%d/')),
                ('photo_5', models.ImageField(upload_to='photos/%y/%m/%d/')),
                ('photo_6', models.ImageField(upload_to='photos/%y/%m/%d/')),
            ],
        ),
    ]
