# Generated by Django 2.1.4 on 2018-12-15 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_auto_20181215_0725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='tuid',
        ),
    ]
